language: node_js
node_js:
 - "16.4.1"

branches:
  only:
    - main

addons:
  chrome: stable

before_script:
  - npm global add @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng build --prod


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: